### ISSUE TITLE
Dataset collection method

### ISSUE THREAD

**Issue by abrac** [transportforcairo/Digital_Cairo#2]
Hi there. 👋🏽

I would like to use your dataset for my research, however I have a few questions regarding the methods used to obtain this dataset:

1. How many data-collectors did you deploy into the field?
2. For how many days were they deployed?
3. Did they collect the data by travelling onboard the various public transport routes, or did they do a "stationary" data collection (i.e. by standing at the bus-stations).

I hope you will be able to answer these questions. Is there an article/publication that I can refer to for further information?

**Comment by tecno14** [comment]
did you get any private answer ?

**Comment by abrac** [comment]
Hi @tecno14. Unfortunately not. If you have some of these answers, would appreciate if you shared, so that I can note it down in my dissertation. But it's no longer critical for me at this stage. I have shifted my focus to other experiments in my research.

**Comment by Melegy90** [comment]
@abrac @tecno14 My apologies, the notifications linked to this account are rarely reviewed anymore. We have moved our data to our data portal, this has the metadata for layers and the most up-to-date publicly available datasets created by TfC:
https://data.transportforcairo.com/

Note that this is an outdated dataset, but in response to your questions:
1. There was a pilot mapping with 15 people and we later settled on 4 field researchers and a field research manager
2. For 2 to 3 months
3. Yes they took every bus from origin to destination (onboard surveys)

**Comment by tecno14** [comment]
@Melegy90 thank you for you replay, actually I was trying to rich you on Facebook and via email from couple days.
Actually, I was wondering if you would mind if I used your data in a free app that may contain some ads to cover operating costs.
Thankyou.

**Comment by tecno14** [comment]
@Melegy90 thank you for you replay, I was trying to reach your company on Facebook and via email from couple days now.
Actually, I was wondering if you would mind if I used your data in a free app that may contain some ads to cover operating costs.
And of course, I will mention your company name as the source of the data with links. 
Thankyou.

**Comment by Melegy90** [comment]
@tecno14 Thanks Wael. I replied to your email just now.
